name: nexhub-backend-workflow

on:
  push:
    branches:
      - "main"

jobs:
  CI-CD:
    runs-on: self-hosted
    steps:
      - name: update system
        run: sudo apt update

      - name: Code-Checkout
        uses: actions/checkout@v4
        
      - name: Remove Docker Container -
        working-directory: .
        run: docker compose down || true

      - name: Build Docker
        working-directory: .
        run: docker compose build


      - name: Docker Run
        working-directory: .
        run: docker compose up -d
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          USER_DATABASE_NAME: users
          TEACHER_DATABASE_NAME: teachers

      - name: Docker Clean
        run: docker system prune -af
